<?php
/*
 * @see       https://www.iscosystem.com.ec
 *
 * @author    Pato Jimenez <pojimenez1@hotmail.com>
 * @test      Adriana Becerra <abbecerra@gmail.com>
 * @copyright Iscosystem Co. ltda.
 * @license   Su uso se restringue a lo descrito en la licencia en la compra del producto
 * @note      clase que permite cargar el menu inicial del sitio
 */

class empresas_view{
    public function __construct(){
        
    }
    function visualizaEm($datos,$filita,$accion,$clases,$open,$id,$sub,$boton){
        if (file_exists($filita)) include ($filita);
        require_once($clases."botones.php");
        $gboto = new botones();
?>


        <div class="">
                <div class="desarrollo">
                <?php
                    if ($accion >0){
                        echo $gboto->tiempos();
                    }
                ?>
                     <div class="titlepag"><blockquote><i class="fa fa-folder fa-lg"></i> <?php echo $tmempresa ?></blockquote></div>
                    <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                                <div class="table-responsive">
                                <?php echo $gboto->get_botonnuevo($boton[0],"ventana(0)"); ?>
                                <br>
                                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                        <th><?php echo $tgcodempre ?></th>
                                        <th><?php echo $tgempresa ?></th>
                                        <th><?php echo $tmail ?></th>
                                        <th><?php echo $tgtelefono ?></th>
                                        <th><?php echo $tgestado ?></th>
                                        <th><?php echo $tgacciones ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    if ($datos){
                                        foreach ($datos as $campos){
                                                $llamado= "ventana('".$rbase."','".$campos['id_institucion']."')";
                                                $llamado1="Borrar('".$rbase."','".$campos['id_institucion']."','".$open."','".$id."','".$sub."')";
                                                echo '<tr><td>'.$campos['id_institucion'].'</td><td>'.htmlentities($campos['name_institucion'], ENT_QUOTES,  'utf-8').'</td><td>'.htmlentities($campos['mail_institucion'], ENT_QUOTES,  'utf-8').'</td><td>'.htmlentities($campos['telefono_institucion'], ENT_QUOTES,  'utf-8').'</td><td>'.htmlentities($campos['estado'], ENT_QUOTES,  'utf-8').'</td><td>'.$gboto->get_botonesgrid($boton[1],$boton[2],"$llamado","$llamado1").'</td></tr>';
                                        }
                                    }
                                    ?>
                                    </tbody>
                                </table>
                                </div>
                    </div>
                    </div><div class="separar"></div>
                </div>
            </div>
        </div>



<!-- Modal -->
    <div class="modal fade in" id="ModalEmpresa" tabindex="-1" role="dialog" aria-labelledby="ModalEmpresaTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            <form action="?open=<?php echo encrypt($open,leer()) ?>&kode=<?php echo encrypt('id='.$id.'&sub='.$sub,leer()) ?>" method="post" enctype="multipart/form-data">  
                <h5 class="modal-title" id="exampleModalLongTitle"><?php echo $tmempresa ?></h5>
            </div>
                <div class="modal-body table-responsive">
                        <div id="alerta"></div>
                        
                        <?php echo '<div class="custom-file">
                                <div class="picture-container">
                                    <div class="picture">
                                        <img src="'.$foto.'" class="picture-src" id="wizardPicturePreview" title=""/>
                                       
                                        <input type="file" id="wizard-picture" accept=".jpg, .png, .jpeg, .svg">
                                    </div>
                                    <h6>Cambiar foto</h6>
                                </div>
                            </div>
                            <input type="hidden" class="form-control" id="txtimage" name="txtimage">
                        <label for="lblcodigo">'.$tgcodempre.':</label>
                        <input type="text" class="form-control" id="txtcodigo" name="txtcodigo" aria-describedby="codigoHelp" placeholder="Campo solo lectura" readonly>
                        <label for="lblnombre">'.$tempresa.':</label>
                        <input type="text" class="form-control" id="txtempresa" name="txtempresa" aria-describedby="codigoHelp" placeholder="Nombre empresa" required>
                        <label for="lbldetalle">'.$tdetalle.':</label>
                        <textarea class="form-control" id="txtdetalle" name="txtdetalle" rows="3" required></textarea>
                        <label for="lblnombre">'.$tdireccion.':</label>
                        <input type="text" class="form-control" id="txtdirecciom" name="txtdirecciom" aria-describedby="codigoHelp" placeholder="Direccion empresa" required>
                        <label for="exampleInputEmail1">'.$tmail.':</label>
                        <input type="email" class="form-control" id="txtmail" name="txtmail" aria-describedby="emailHelp" placeholder="Ingrese email" required>
                        <label for="exampleInputEmail1">'.$tgtelefono.':</label>
                        <input type="text" class="form-control" id="txttelefono" name="txttelefono" aria-describedby="emailHelp" placeholder="Número de teléfono" required>
                        <label class="my-1 mr-2" for="inlineFormCustomSelectPref">'.$tgestado.':</label>'; ?>
                        <select class="form-control custom-select my-1 mr-sm-2" id="cmbestado" name="cmbestado">
                            <option value="0">Inactivo</option>
                            <option value="1">Activo</option>
                        </select>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $bcerrar ?></button><?php echo $gboto->get_guardar(1,"") ?>
          </div>
        </form>
        </div>    
      </div>
    </div>

    <?php echo $gboto->get_ventana($accion) ?>
    <script src="<?php echo $rbase ?>/empresas.js"></script>
<?php
    }
}
?>