<?php
/*
 * @see       https://www.iscosystem.com.ec
 *
 * @author    Pato Jimenez <pojimenez1@hotmail.com>
 * @test      Adriana Becerra <abbecerra@gmail.com>
 * @copyright Iscosystem Co. ltda.
 * @license   Su uso se restringue a lo descrito en la licencia en la compra del producto
 * @note      clase que permite cargar el menu inicial del sitio
 */
class entregainv_view{
    public function __construct(){

    }
    
    function visualizaEInv($clases,$lenguaje,$botones,$especialistas,$inventario,$userid,$entregas){
        if (file_exists($lenguaje)) include ($lenguaje);
        require_once($clases."botones.php");
        $gboto = new botones();
        echo $gboto->get_mensajes();
    ?>
        <script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
        <link rel='stylesheet prefetch' href='css/bootstrap-select.min.css'>
        <script src="js/bootstrap-select.min.js"></script>
        <script src="js/jQuery.print.js"></script> 

        <div class="container">
            <div class="desarrollo">
                    <div class="col-md-12"><div class="titlepag"><blockquote><i class="fa fa-user fa-lg"></i> <?php echo strtoupper($tentrega) ?></blockquote></div></div>
                    <input type="hidden" class="form-control" id="idespecialista" name="idespecialista" value ="0" required>
                    <table class="table">
                        <tr><td>
                            <?php 
                                echo '<script>$(document).ready(function(){ $("#wizardPicturePreview").attr("src","images/noimagen.jpg"); });</script>
                                <div class="dual-list list-left">
                                <div class="well text-left">
                                    <h4>'.$tespecialita.':</h4>
                                    <div class="row">
                                        <div class="col-md-8">                                    
                                            <div class="input-group">
                                                <input type="text" name="SearchDualList" class="form-control" placeholder="search" /> 
                                                <span class="input-group-addon glyphicon glyphicon-search"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <ul class="list-group" id="especialista">';
                                            foreach ($especialistas as $valus)
                                                echo '<li id="liespeci" class="list-group-item"> <input class="form-check-input me-1 slectOne" id="chespecial" name="chespecial" type="checkbox" value="'.$valus['id_usuarios'].'"> '.$valus['nombres_usuarios'].' '.$valus['apellidos_usuarios'].'</li>';   
                                    echo '</ul>
                                    </div>
                                 </div>';



                                 echo '<script>$(document).ready(function(){ $("#wizardPicturePreview").attr("src","images/noimagen.jpg"); });</script>
                                 <div class="dual-list list-left">
                                 <div class="well text-left">
                                     <h4>'.$tlpedidos.':</h4>
                                     <input type="date" class="form-control" id="txtfech" name="txtfech" placeholder="fecha de consulta" value="'.date('Y-m-d').'" required>
                                     <div class="row">
                                         <div class="col-md-8">                                    
                                             <div class="input-group">
                                                 <input type="text" name="SearchDualList" class="form-control" placeholder="search" /> 
                                                 <span class="input-group-addon glyphicon glyphicon-search"></span>
                                             </div>
                                         </div>
                                     </div>
                                     <ul class="list-group" id="entregas">';
                                        foreach($entregas as $value){
                                            $link = $value['producto'].'-'.$value['entrega'].' '.$value['recibe'].'-'.$value['fecha'].'-'.$value['total'];
                                            echo '<li id="lientrega" class="list-group-item"> <input class="form-check-input me-1 slectTwo" id="chentrega" name="chentrega" type="checkbox" value="'.$link.'"> '.$value['recibe'].' - '.$value['producto'].'</li>';   
                                        }
                                echo '</ul>
                                     '.$gboto->get_boton(1,"Re-Imprimir","impresion()",2).' '.$gboto->get_eliminar($botones[2],"eliminar_cliente()").'
                                     </div>
                                  </div>

                        </td><td>';

                        echo '<div class="well text-rigth">
                                <div class="row">
                                    <div class="col-xs-4">
                                        <h4>'.$tproducto.':</h4>
                                        <select id="selecpe" name="selecpe" onchange="recuperar_campos(this.value)" class="selectpicker show-menu-arrow" 
                                        data-style="form-control" 
                                        data-live-search="true" 
                                        title="Pacientes">
                                            <option data-tokens value="0">Seleccione</option>';
                                            foreach ($inventario as $valus){
                                                echo '<option data-tokens value="'.$valus['id_inventario'].'">'.$valus['inventario_nombre'].'</option>';
                                            }
                                        echo '</select>
                                    </div>

                                    <div class="col-xs-3">
                                        <h4>'.$tcantida.':</h4>
                                        <input type="number" class="form-control" onchange="validar_existencias(this.value)" id="txtcanti" name="txtcanti" value="1" min="1" max="100" aria-describedby="codigoHelp" placeholder="Cantidad a entregar" required>
                                    </div>
                                    <div class="col-xs-3">
                                        <h4>'.$tobserva.':</h4>
                                        <input type="text" class="form-control" id="txtobserva" name="txtobserva" aria-describedby="codigoHelp" placeholder="Observaciones" required>
                                    </div>
                                    <br><br><div class="col-xs-2">'.$gboto->get_boton(1,"Agregar","agregar_prod()",2).'</div>
                                </div>
                               <div id="elementos"></div>
                            </div>

                        <script>$(document).ready(function(){ $("#wizardPicturePreview").attr("src","images/noimagen.jpg"); });</script>
                        
                        <div id="frmprod">
                            <table class="table"><tr><td>
                            <label for="lblnombre">'.$tnombre.':</label>
                            <input type="text" class="form-control" id="txtnombre" name="txtnombre" aria-describedby="codigoHelp" placeholder="Nombre producto" readonly required>
                            </td><td>
                            <label for="lbldetalle">'.$tcantida.':</label>
                            <input type="number" class="form-control" id="txtcantidad" name="txtcantidad" aria-describedby="codigoHelp" placeholder="Cantidad" readonly required>
                            </td><td rowspan="2">
                                <div class="picture">
                                    <img src="'.$foto.'" class="picture-src" id="wizardPicturePreview" title=""/>
                                </div>
                            </td></tr><tr><td><label for="lblnombre">'.$tprecio.':</label>
                            <input type="text" class="form-control" id="txtprecio" name="txtprecio" aria-describedby="codigoHelp" placeholder="Precio" readonly required>
                            </td><td><label for="lblnombre">'.$tfechaco.':</label>
                            <input type="text" class="form-control" id="txtfecha" name="txtfecha" aria-describedby="emailHelp" placeholder="Fecha compra" readonly required>
                            </td></tr></table>

                            <label for="lblnombre">'.$tubica.':</label>
                            <textarea class="form-control" class="form-control" id="txtubica" name="txtubica" rows="3" readonly></textarea>
                            <label for="lblnombre">'.$tdescrip.':</label>
                            <textarea class="form-control" class="form-control" id="txtdescrip" name="txtdescrip" rows="3" readonly></textarea><br><br>'
                            .$gboto->get_botonnuevop($botones[0],"limpiar()").' '.$gboto->get_guardar($botones[1],"entregar(".$userid.")").'
                        </div>
                        </td></tr><tr><td></td><td>
                </td></tr><table class="table"><tr align="center"><td>
                </td></tr></table>';
            ?>
            <form id="formahis" method="post" action="">
                <input type="hidden" autocomplete="off" id="idp" name="idp">
            </form>

                    <div id="impresion">
                        <label for="lblfecha">Fecha de entrega: </label><br>
                        <label for="lbldetalle">aqui el texto o contenido de la entrega</label><br>
                        <label for="lblfirma1">firma1</label><br>
                        <label for="lblfirma2">firma2</label><br>
                    <div>

            </div>
        </div>
        <script src="<?php echo $rbase ?>/entinv.js"></script>

       
    <?php
    }
}
?>

