
<?php
/**
 * class.
 * PHP Version 8.0
 *
 * @see       https://www.iscosystem.com.ec
 *
 * @author    Pato Jimenez <pojimenez1@hotmail.com>
 * @test      Adriana Becerra <abbecerra@gmail.com>
 * @copyright Iscosystem Co. ltda.
 * @license   Su uso se restringue a lo descrito en la licencia en la compra del producto
 * @note      clase que permite cargar el menu inicial del sitio
 */

class home_view{
    public function __construct(){

    }

    function visualizar($datos,$nuevis,$lenguaje){
        if (file_exists($lenguaje)) include ($lenguaje);
        if ($nuevis=='new=1') echo '<script type="text/javascript">   $(function(){$("#ModalEmpresa").modal({ backdrop: "static", keyboard: false });}); </script>'; 
?>
<div class="container">
    <div class="home desarrollo justify-content-center"></div>
</div>

<div class="modal fade in" id="ModalEmpresa" tabindex="-1" role="dialog" aria-labelledby="ModalEmpresaTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="exampleModalLongTitle"><?php echo $tituven ?></h5>
            </div>
                <div class="modal-body table-responsive">
                       
                <img src="<?php echo $_SESSION['foto_us']; ?>" name="aboutme" width="140" height="140" class="img-circle"></a>
                <h3 class="media-heading"><?php echo $twelcome. ' '.$_SESSION['usernc'] ?></small></h3>
                <span><?php echo $tparte1. ' '.$titule ?>.</span>
                <span><?php echo $tparte2 ?></span>
              
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $bcerrar ?></button>
          </div>
        </form>
        </div>    
      </div>
    </div>
<?php }
}
?>


   
       


