<?php
/*
 * @see       https://www.iscosystem.com.ec
 *
 * @author    Pato Jimenez <pojimenez1@hotmail.com>
 * @test      Adriana Becerra <abbecerra@gmail.com>
 * @copyright Iscosystem Co. ltda.
 * @license   Su uso se restringue a lo descrito en la licencia en la compra del producto
 * @note      clase que permite cargar el menu inicial del sitio
 */

class inventario_view{
    public function __construct(){

    }

    function visualizaInv ($clases,$configura,$botones,$productos,$boton,$accion,$open,$id,$sub){
        if (file_exists($configura)) include ($configura);
        require_once($clases."botones.php");
        $gboto = new botones();

        echo $gboto->get_mensajes();
    ?>

        <div class="">
                <div class="desarrollo">
                <?php
                    if ($accion >0){
                        echo $gboto->tiempos();
                    }
                ?>
                     <div class="titlepag"><blockquote><i class="fa fa-folder fa-lg"></i> <?php echo $tinventar ?></blockquote></div>
                    <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
                                <div class="table-responsive">
                                <?php echo $gboto->get_botonnuevo($boton[0],"ventana(0)"); ?>
                                <br>
                                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                        <th><?php echo $tnombre ?></th>
                                        <th><?php echo $tcantida ?></th>
                                        <th><?php echo $tprecio ?></th>
                                        <th><?php echo $tfechaco ?></th>
                                        <th><?php echo $tgacciones ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    if ($productos){
                                        foreach ($productos as $campos){
                                                $llamado= "ventana('".$campos['id_inventario']."')";
                                                $llamado1="Borrar('".$campos['id_inventario']."')";
                                                echo '<tr><td>'.$campos['nombre'].'</td><td>'.htmlentities($campos['cantidad'], ENT_QUOTES,  'utf-8').'</td><td>'.htmlentities($campos['precio'], ENT_QUOTES,  'utf-8').'</td><td>'.htmlentities($campos['fecha'], ENT_QUOTES,  'utf-8').'</td><td>'.$gboto->get_botonesgrid($boton[1],$boton[2],"$llamado","$llamado1").'</td></tr>';
                                        }
                                    }
                                    ?>
                                    </tbody>
                                </table>
                                </div>
                    </div>
                    </div><div class="separar"></div>
                </div>
            </div>
        </div>



<!-- Modal -->
    <div class="modal fade in" id="ModalEmpresa" tabindex="-1" role="dialog" aria-labelledby="ModalEmpresaTitle" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            <form action="?open=<?php echo encrypt($open,leer()) ?>&kode=<?php echo encrypt('id='.$id.'&sub='.$sub,leer()) ?>"  method="post" enctype="multipart/form-data">  
                <h5 class="modal-title" id="exampleModalLongTitle"><?php echo $tinventar ?></h5>
            </div>
                <div class="modal-body table-responsive" id="frminventario" name="frminventario">
                        <div id="alerta"></div>
                        
                        <?php echo '<div class="custom-file">
                                <div class="picture-container">
                                    <div class="picture">
                                        <img src="'.$foto.'" class="picture-src" id="wizardPicturePreview" title=""/>
                                        <input type="file" id="wizard-picture" accept=".jpg, .png, .jpeg, .svg">
                                    </div>
                                    <h6>Cambiar foto</h6>
                                </div>
                            </div>
                            <input type="hidden" class="form-control" id="txtimage" name="txtimage">
                        <label for="lblcodigo">'.$tgcodempre.':</label>
                        <input type="text" class="form-control" id="txtcodigo" name="txtcodigo" aria-describedby="codigoHelp" placeholder="Campo solo lectura" readonly>
                        <label for="lblnombre">'.$tnombre.':</label>
                        <input type="text" class="form-control" id="txtnombre" name="txtnombre" aria-describedby="codigoHelp" placeholder="Nombre" required>
                        <label for="lbldetalle">'.$tcantida.':</label>
                        <input type="number" class="form-control" id="txtcantidad" name="txtcantidad" aria-describedby="codigoHelp" placeholder="Cantidad" required>
                        <label for="lbldetalle">'.$tprecio.':</label>
                        <input type="number" class="form-control" id="txtprecio" name="txtprecio" aria-describedby="codigoHelp" step="0.01" pattern="^\d+(?:\.\d{1,2})?$" placeholder="Precio" required>
                        <label for="lblnombre">'.$tfechaco.':</label>
                        <input type="date" class="form-control" id="txtfecha" name="txtfecha" aria-describedby="codigoHelp" placeholder="Fecha compra" required>
                        <label for="exampleInputEmail1">'.$tubica.':</label>
                        <textarea class="form-control" id="txtubica" name="txtubica" rows="3"></textarea>
                        <label for="exampleInputEmail1">'.$tdescrip.':</label>
                        <textarea class="form-control" id="txtdescrip" name="txtdescrip" rows="3"></textarea>';?>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $bcerrar ?></button><?php echo $gboto->get_guardar(1,"") ?>
          </div>
        </form>
        </div>    
      </div>
    </div>

    <?php echo $gboto->get_ventana($accion) ?>
    <script src="<?php echo $rbase ?>/inventario.js"></script>

    <?php
    }
}
?>
